import { IProduct, Product, ProductStatus } from "@/interface/product.interface"

export const PLACEHOLDER_PRODUCTS: Product[] = [
  {
    id: "PRD-001",
    name: "Wireless Headphones",
    category: "Electronics",
    price: 79.99,
    stock: 42,
    image: "/images/headphones.jpg",
  },
  {
    id: "PRD-002",
    name: "Running Sneakers",
    category: "Footwear",
    price: 54.99,
    stock: 18,
    image: "/images/sneakers.jpg",
  },
  {
    id: "PRD-003",
    name: "Ceramic Coffee Mug",
    category: "Kitchen",
    price: 14.99,
    stock: 75,
    image: "/images/mug.jpg",
  },
  {
    id: "PRD-004",
    name: "Hardcover Notebook",
    category: "Stationery",
    price: 12.49,
    stock: 5,
    image: "/images/notebook.jpg",
  },
  {
    id: "PRD-005",
    name: "Resistance Band Set",
    category: "Fitness",
    price: 24.99,
    stock: 30,
    image: "/images/bands.jpg",
  },
  {
    id: "PRD-006",
    name: "Soy Wax Candle",
    category: "Home Decor",
    price: 19.99,
    stock: 8,
    image: "/images/candle.jpg",
  },
  {
    id: "PRD-007",
    name: "Bluetooth Speaker",
    category: "Electronics",
    price: 49.99,
    stock: 20,
    image: "/images/speaker.jpg",
  },
  {
    id: "PRD-008",
    name: "Yoga Mat",
    category: "Fitness",
    price: 29.99,
    stock: 15,
    image: "/images/yogamat.jpg",
  },
  {
    id: "PRD-009",
    name: "Stainless Steel Water Bottle",
    category: "Outdoors",
    price: 22.99,
    stock: 25,
    image: "/images/waterbottle.jpg",
  },
  {
    id: "PRD-010",
    name: "LED Desk Lamp",
    category: "Home Decor",
    price: 34.99,
    stock: 10,
    image: "/images/desklamp.jpg",
  },
  {
    id: "PRD-011",
    name: "Portable Power Bank",
    category: "Electronics",
    price: 39.99,
    stock: 12,
    image: "/images/powerbank.jpg",
  },
  {
    id: "PRD-012",
    name: "Leather Wallet",
    category: "Accessories",
    price: 49.99,
    stock: 20,
    image: "/images/wallet.jpg",
  },
  {
    id: "PRD-013",
    name: "Scented Bath Bombs",
    category: "Beauty",
    price: 19.99,
    stock: 30,
    image: "/images/bathbombs.jpg",
  },
  {
    id: "PRD-014",
    name: "Wireless Mouse",
    category: "Electronics",
    price: 24.99,
    stock: 18,
    image: "/images/mouse.jpg",
  },
  {
    id: "PRD-015",
    name: "Cotton T-Shirt",
    category: "Apparel",
    price: 14.99,
    stock: 50,
    image: "/images/tshirt.jpg",
  },
]


